# Generated by Django 5.1.2 on 2025-02-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
    ]
