# Generated by Django 5.1.6 on 2025-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0002_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocks_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
